### PR TITLE
Fixed missing import in example, fixed markdown formatting

### PR DESCRIPTION
**Pull request by Laptopmini**

### CODE REVIEW

**Comment by Laptopmini** [comment]
No merge?

**Comment by marstorp** [comment]
Maybe I'm blind but I don't see what's missing that's been added, I only see formatting changes and the added `shell` before `npm install st-schema`.
Can you point out the important fix in the PR.

**Comment by Laptopmini** [comment]
https://github.com/SmartThingsCommunity/st-schema-nodejs#appjs

this example is invalid

**Comment by marstorp** [comment]
Cool, but why was `shell` added before `npm install st-schema`.

**Comment by Laptopmini** [comment]
https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md040---fenced-code-blocks-should-have-a-language-specified

**Pull request closed without merging**
